name: Sudoku
description: Single page web app that implements a single player game like sudoku.
version: 1.0.0
#author: Dirk Teschner <di_teschner@yahoo.de>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  browser: ^0.10.0
  collection: any
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter
